collections:
  - name: azure.azcollection
    version: 1.12.0
  - name: amazon.aws
    version: 3.3.0
  # For route53
  - name: community.aws
    version: 3.2.0
  - name: google.cloud
    version: 1.0.2
