collections:
  - name: azure.azcollection
    version: 1.16.0
  - name: amazon.aws
    version: 3.5.1
  # For route53
  - name: community.aws
    version: 3.6.0
  - name: google.cloud
    version: 1.1.3
