collections:
  - name: azure.azcollection
    version: 1.10.0
  - name: amazon.aws
    version: 2.1.0
  # For route53
  - name: community.aws
    version: 2.1.0
  - name: google.cloud
    version: 1.0.2
