collections:
  # A mix of the two until amazon.aws absorbs all the modules required in this repo.
  - name: amazon.aws
    version: 1.5.0
  - name: community.aws
    version: 1.5.0
  - name: azure.azcollection
    version: 1.10.0
  - name: google.cloud
    version: 1.0.2
  - name: kubernetes.core
    version: 2.1.1
