---
#image_version: 1.2
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/creator-ee'

ansible_config: './ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
