---
#image_version: 4.1
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8

additional_build_steps:
  prepend_galaxy:
    - ADD ../ansible.cfg ~/.ansible.cfg

dependencies:
  galaxy: requirements.yml
  python:
    - pyats[library]
    - genie
    - ansible-pylibssh
  system: bindep.txt
