collections:
    - name: community.general
      version: 4.0.1
    - name: cisco.ios
      version: 2.8.0
    - name: cisco.nxos
      version: 2.9.1
    - name: cisco.iosxr
      version: 2.9.0
    - name: ansible.netcommon
      version: 2.6.0   
    - name: arista.eos
      version: 4.1.2
