collections:
  - name: community.general
    version: 7.1.0
  - name: check_point.mgmt
    version: 5.1.1
  - name: cisco.asa
    version: 4.0.1
  - name: cisco.ise
    version: 2.4.1
  - name: ansible.netcommon
    version: 5.0.0
  - name: f5networks.f5_modules
    version: 1.25.0
  - name: paloaltonetworks.panos
    version: 2.13.2
  - name: f5networks.f5_bigip
    version: 1.13.0
