collections:
  - name: ansible.controller
    version: 4.3.0
  - name: redhat_cop.aap_utilities
    version: 2.2.2
  - name: redhat_cop.ah_configuration
    version: 0.9.2
  - name: redhat_cop.controller_configuration
    version: 2.1.9
  - name: community.general
    version: 6.0.1