collections:
  - name: ansible.controller
    version: 4.3.0
  - name: redhat_cop.aap_utilities
    version: 2.2.4
  - name: redhat_cop.ah_configuration
    version: 1.1.1
  - name: redhat_cop.controller_configuration
    version: 2.4.0
  - name: community.general
    version: 7.1.0
