collections:
  - name: amazon.aws
    version: 3.3.0
  - name: community.crypto
    version: 2.1.0
  - name: ansible.posix
    version: 1.4.0
  - name: community.general
    version: 5.1.1
  - name: community.libvirt
    version: 1.1.0
