---
#image_version: 1.0
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/creator-ee'

ansible_config: './ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  append:
    - ADD https://cdn.teleport.dev/teleport-15.0.2-1.x86_64.rpm /tmp/teleport-15.0.2-1.x86_64.rpm
    - RUN chmod u+x /tmp/teleport-15.0.2-1.x86_64.rpm
    - RUN microdnf install -y /tmp/teleport-15.0.2-1.x86_64.rpm
