collections:
    - name: amazon.aws
      version: 6.0.0
    - name: community.general
      version: 7.0.1
    - name: cisco.ios
      version: 3.3.2
    - name: cisco.nxos
      version: 3.2.0
    - name: cisco.iosxr
      version: 3.3.1
    - name: cisco.asa
      version: 4.0.0
    - name: ansible.netcommon
      version: 4.1.0
    - name: servicenow.itsm
      version: 2.2.0
