# Workflow Name
name: General DE build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches:
      - master
    paths:
      - 'de-general-image/**'

  # Schedule workflow run at 04:00 on Sunday
  schedule:
    - cron: '0 8 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-deploy-workflow:
    uses:  nleiva/ee-builds/.github/workflows/deploy_v3.yml@master
    with:
      EE_FOLDER_NAME: 'de-general-image'
      EE_IMAGE_TAG: 'latest'
      QUAY_USER: 'nleiva'
    secrets:
      REDHAT_USERNAME: ${{ secrets.REDHAT_USERNAME }}
      REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      AH_TOKEN: ${{ secrets.AH_TOKEN }}
