# Workflow Name
name: General Community EE build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches:
      - master
    paths:
      - 'ee-general-community/**'

  # Schedule workflow run at 01:00 on Sunday
  schedule:
    - cron: '0 7 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-deploy-workflow:
    uses: nleiva/ee-builds/.github/workflows/deploy.yml@master
    with:
      EE_FOLDER_NAME: 'ee-general-community'
      EE_IMAGE_TAG: 'latest'
      QUAY_USER: 'nleiva2'
    secrets:
      REDHAT_USERNAME: ${{ secrets.REDHAT_USERNAME }}
      REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      AH_TOKEN: ${{ secrets.AH_TOKEN }}
